name: Daily Selenium Test Run

on:
  workflow_dispatch:  # This will enable manual triggering of the workflow

jobs:
  test:
    name: Run Selenium Tests
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'  # Replace with the desired Java version (e.g., 8, 11, 16, etc.)
          distribution: 'adopt'  # Specify the distribution of the JDK (e.g., adopt, adopt-openj9, corretto, graalvm)

      - name: Cache Maven dependencies
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}

      - name: Build and run tests
        run: |
          mvn test

      - name: Install Java (required for Allure)
        uses: actions/setup-java@v1
        with:
          java-version: '12' # You can choose the appropriate version.

      - name: Download and install Allure command-line tool
        run: |
          Expand-Archive allure.zip -DestinationPath $env:ALLURE_HOME
          echo "ALLURE_HOME=$env:ALLURE_HOME" >> $env:GITHUB_ENV
          echo "PATH=$env:ALLURE_HOME\bin;$env:PATH" >> $env:GITHUB_ENV
        shell: pwsh

      # Run your tests and generate Allure results here

      - name: Generate Allure Report
        run: allure generate allure-results -o allure-report --clean

      - name: Get Allure history
        uses: actions/checkout@v2
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Deploy report to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.MY_TC }}
          publish_branch: gh-pages
