name: Daily Selenium Test Run

on:
  schedule:
    - cron: '0 0 * * *'  # Schedule the workflow to run daily at midnight UTC (adjust according to your timezone)

jobs:
  test:
    name: Run Selenium Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'  # Replace with the desired Java version (e.g., 8, 11, 16, etc.)

      - name: Cache Maven dependencies
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}

      - name: Build and run tests
        run: |
          mvn test

      - name: Generate Allure report
        run: |
          allure generate allure-results --clean
