name: Daily Selenium Test

on: [pull_request, push]

jobs:
  test:
    name: Run Selenium Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'  # Replace with the desired Java version (e.g., 8, 11, 16, etc.)
          distribution: 'adopt'  # Specify the distribution of the JDK (e.g., adopt, adopt-openj9, corretto, graalvm)

      - name: Cache Maven dependencies
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}

      - name: Build and run tests
        run: |
          cd APFGHA # Assuming APFGHA is the root directory of your project
          mvn test

      - name: Generate Allure report
        run: |
          cd APFGHA # Assuming APFGHA is the root directory of your project
          npm install -g allure-commandline
          allure --version
          allure generate allure-results --clean

      - name: Get Allure history
        uses: actions/checkout@v2
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: APFGHA/gh-pages # Assuming gh-pages directory is within APFGHA directory

      - name: Allure Report action from the marketplace
        uses: simple-elf/allure-report-action@master
        if: always()
        with:
          allure_results: APFGHA/allure-results # Assuming allure-results directory is within APFGHA directory
          allure_history: APFGHA/allure-history # Assuming allure-history directory is within APFGHA directory
          keep_reports: 1

      - name: Deploy report to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.MY_TC }}
          publish_branch: gh-pages
          publish_dir: APFGHA/allure-results-${{ github.run_number }} # Assuming allure-results directory is within APFGHA directory
