name: Daily Selenium Test

on: [pull_request, push]

jobs:
  test:
    name: Run Selenium Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Cache Maven dependencies
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}

      - name: Build and run tests
        run: mvn test
        working-directory: APFGHA

      - name: Generate Allure report
        run: |
          npm install -g allure-commandline
          allure --version
          allure generate allure-results --clean
        working-directory: APFGHA # Assuming APFGHA is the root directory of your project

      - name: Get Allure history
        uses: actions/checkout@v2
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages # Assuming gh-pages directory is within the repository root

      - name: Allure Report action from the marketplace
        uses: simple-elf/allure-report-action@master
        if: always()
        with:
          allure_results: APFGHA/allure-results # Assuming allure-results directory is within the root directory
          allure_history: APFGHA/allure-history # Assuming allure-history directory is within the root directory
          keep_reports: 1

      - name: Deploy report to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.MY_TC }}
          publish_branch: gh-pages
          publish_dir: APFGHA/allure-results-${{ github.run_number }} # Assuming allure-results directory is within the root directory
